version: '3.7'

services:

  gui:
    build: ./gui
    container_name: gui
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mqtt_broker
      - knowledge
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  planner:
    build: ./planner
    container_name: planner
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mqtt_broker
      - knowledge
      - robot
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  knowledge:
    build: ./knowledge
    container_name: knowledge
    restart: always
    ports:
      - 5000:5000
    networks:
      - warehouse
  monitor:
    build: ./monitor
    container_name: monitor
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mqtt_broker
      - knowledge
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  analyzer:
    build: ./analyzer
    container_name: analyzer
    restart: always
    ports:
      - 8083:8083
    depends_on:
      - mqtt_broker
      - knowledge
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  executor:
    build: ./executor
    container_name: executor
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - mqtt_broker
      - knowledge
      - planner
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  robot:
    build: ./robot
    container_name: robot
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mqtt_broker
      - knowledge
      - monitor
    volumes:
      - ./warehouse.conf:/usr/src/app/warehouse.conf
    networks:
      - warehouse
  mqtt_broker:
    image: eclipse-mosquitto:2.0.10
    container_name: mqtt_broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    ports:
      - 1883:1883
      - 8001:8001
    networks:
      - warehouse

networks:
  warehouse:
